'use client';

import Link from 'next/link';
import { Footer } from '@/components/footer';

type Profile = {
  name: string;
  subtitle: string;
  accent: string;
  soft: string;
  mechanismTitle: string;
  mechanism: string;
  highlightTitle: string;
  highlight: string;
  signs: string[];
  shortTerm: string[];
  longTerm: string[];
  riskTitle: string;
  risk: string;
  emergency: string;
  emergencyNote: string;
};

export function SubstanceProfilePage({ profile }: { profile: Profile }) {
  const tabs = [
    ['Signs of Use', profile.signs],
    ['Short Term', profile.shortTerm],
    ['Long Term', profile.longTerm],
  ] as const;

  return (
    <>
      <div className="bg-red-600 px-4 py-3 text-center font-bold text-white">CALL <a href="tel:211" className="underline">2-1-1</a> FOR LOCAL RESOURCES · LIFE-THREATENING EMERGENCIES: <a href="tel:911" className="underline">9-1-1</a></div>
      <header className="border-b-2 border-teal-200 bg-white shadow-sm">
        <div className="mx-auto flex max-w-6xl flex-col items-center gap-4 px-4 py-10 text-center">
          <p className={`text-sm font-bold uppercase tracking-[0.3em] ${profile.accent}`}>Substance education guide</p>
          <h1 className={`text-6xl font-bold ${profile.accent}`}>{profile.name}</h1>
          <p className="max-w-3xl text-2xl text-gray-600">{profile.subtitle}</p>
          <Link href="/education" className="rounded-lg bg-gray-700 px-6 py-2 font-bold text-white transition hover:bg-gray-800">Back to Education</Link>
        </div>
      </header>
      <main className="mx-auto max-w-6xl px-4 py-12">
        <section className="mb-10 grid gap-8 md:grid-cols-2">
          <div className={`rounded-lg border-l-8 ${profile.accent.replace('text-', 'border-')} bg-white p-8 shadow-sm`}>
            <h2 className="mb-4 text-3xl font-bold text-gray-900">{profile.mechanismTitle}</h2>
            <p className="leading-relaxed text-gray-700">{profile.mechanism}</p>
          </div>
          <div className={`rounded-lg ${profile.accent.replace('text-', 'bg-')} p-8 text-center text-white`}>
            <h2 className="mb-4 text-sm font-bold uppercase tracking-widest">Key point</h2>
            <p className="text-3xl font-bold">{profile.highlightTitle}</p>
            <p className="mt-3 leading-relaxed">{profile.highlight}</p>
          </div>
        </section>
        <section className="mb-10 rounded-lg bg-white p-8 shadow-sm">
          <h2 className="mb-6 text-3xl font-bold text-gray-900">Recognize the effects</h2>
          <div className="grid gap-8 md:grid-cols-3">
            {tabs.map(([title, items]) => (
              <div key={title}>
                <h3 className={`mb-4 text-xl font-bold ${profile.accent}`}>{title}</h3>
                <ul className="space-y-3 text-gray-700">{items.map((item) => <li key={item} className={`border-l-4 ${profile.accent.replace('text-', 'border-')} ${profile.soft} p-3`}>{item}</li>)}</ul>
              </div>
            ))}
          </div>
        </section>
        <section className="grid gap-8 md:grid-cols-2">
          <div className={`rounded-lg border-t-8 ${profile.accent.replace('text-', 'border-')} ${profile.soft} p-8`}>
            <h2 className="mb-4 text-2xl font-bold text-gray-900">{profile.riskTitle}</h2>
            <p className="leading-relaxed text-gray-700">{profile.risk}</p>
          </div>
          <div className="rounded-lg border-t-8 border-red-600 bg-red-50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-red-800">Identifying an emergency</h2>
            <p className="mb-4 text-gray-700">{profile.emergency}</p>
            <p className="rounded bg-red-100 p-3 text-sm font-bold uppercase text-red-900">{profile.emergencyNote}</p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

export type { Profile };

export const profiles = {
  alcohol: { name: 'Alcohol', subtitle: 'CNS Depressant & GABA-A Positive Allosteric Modulator', accent: 'text-amber-700', soft: 'bg-amber-50', mechanismTitle: 'Origins & Action', mechanism: 'Ethanol enhances GABA-mediated inhibition while suppressing excitatory NMDA glutamate receptors, producing central nervous system depression, motor impairment, and cognitive slowing.', highlightTitle: 'Alcoholic blackout', highlight: 'Anterograde amnesia can occur when rapid blood alcohol elevation blocks hippocampal NMDA receptors.', signs: ['Unsteady gait or loss of balance', 'Slurred speech and delayed responses', 'Involuntary eye movements', 'Facial flushing and bloodshot eyes', 'Lowered inhibitions', 'Loss of fine motor skills'], shortTerm: ['Mild euphoria and disinhibition', 'Impaired motor control', 'Nausea and gastric irritation', 'Heat loss from vasodilation', 'Cognitive slowing', 'Respiratory depression at high BAC'], longTerm: ['Liver cirrhosis and failure', 'Wernicke-Korsakoff syndrome', 'Cardiomyopathy and arrhythmias', 'Increased gastrointestinal cancer risk', 'Severe physical dependence', 'Cerebral cortical atrophy'], riskTitle: 'Hepatic & neurotoxicity', risk: 'Chronic heavy ethanol consumption can cause fatty liver, hepatitis, and cirrhosis. Thiamine deficiency can cause Wernicke-Korsakoff syndrome and permanent memory loss.', emergency: 'Unconsciousness, breathing under 8 breaths per minute, clammy skin, or continuous vomiting while stuporous require immediate help.', emergencyNote: 'Risk: Delirium tremens and fatal respiratory depression' } satisfies Profile,
  'crack-cocaine': { name: 'Crack Cocaine', subtitle: 'CNS Stimulant & Freebase Monoamine Reuptake Inhibitor', accent: 'text-red-700', soft: 'bg-red-50', mechanismTitle: 'Origins & Inhalation', mechanism: 'Crack is the freebase form of cocaine hydrochloride. Inhalation produces near-instant pulmonary absorption and a rapid flood of dopamine that reinforces repeated use.', highlightTitle: 'The rush & crash', highlight: 'The intense euphoria lasts about five minutes and is followed by a steep crash that can drive compulsive redosing.', signs: ['Dilated pupils', 'Charred fingers or lips', 'Rapid, hyper-vigilant speech', 'Sweating and hypertension', 'Intense paranoia', 'Immediate depressive crash'], shortTerm: ['Instant euphoric energy rush', 'Severe vasoconstriction', 'Heart rate and blood pressure spike', 'Suppressed fatigue and hunger', 'Anxiety and paranoid psychosis', 'Dysphoria and craving'], longTerm: ['Crack lung and alveolar hemorrhage', 'Coronary artery disease', 'Heart attack or stroke', 'Severe dental decay', 'Dopamine receptor down-regulation', 'Chronic paranoid psychosis'], riskTitle: 'Crack lung & cardiotoxicity', risk: 'Inhaled thermal products can damage alveolar membranes, causing acute lung injury and hemorrhage. Severe coronary vasoconstriction can cause a sudden heart attack.', emergency: 'Crushing chest pain, extreme hyperthermia, violent paranoia, or seizures require emergency care.', emergencyNote: 'Hazard: Cocaethylene formation when combined with alcohol' } satisfies Profile,
  mdma: { name: 'MDMA', subtitle: 'Empathogen, Entactogen & Monoamine Transporter Substrate', accent: 'text-pink-700', soft: 'bg-pink-50', mechanismTitle: 'Origins & Mechanism', mechanism: 'MDMA reverses monoamine transporters, especially SERT, increasing serotonin, dopamine, and oxytocin and producing empathy, sociability, and sensory enhancement.', highlightTitle: 'Tuesday blues', highlight: 'Temporary depletion of serotonin stores can contribute to low mood 48–72 hours after use.', signs: ['Severe pupil dilation', 'Jaw clenching and lip biting', 'Involuntary eye movements', 'Profuse sweating and elevated skin temperature', 'Unusual tactile affection and empathy', 'Heightened light and sound sensitivity'], shortTerm: ['Emotional openness and warmth', 'Heightened sensory perception', 'Elevated heart rate and blood pressure', 'Urinary retention', 'Dry mouth and appetite loss', 'Fatigue, depression, and insomnia afterward'], longTerm: ['Serotonergic axon terminal damage', 'Down-regulation of serotonin receptors', 'Verbal working-memory deficits', 'Mood and anxiety disorders', 'Sleep disruption'], riskTitle: 'Hyperthermia & hyponatremia', risk: 'MDMA can disrupt thermoregulation and water balance. Dancing, heat, and excessive water intake increase the risk of heatstroke or hyponatremia.', emergency: 'Temperature above 104°F, confusion, muscle rigidity, severe headache, vomiting, or altered consciousness require emergency care.', emergencyNote: 'Fatal risk: Serotonin syndrome with SSRIs or MAOIs' } satisfies Profile,
  psilocybin: { name: 'Psilocybin', subtitle: 'Tryptamine Psychedelic & 5-HT2A Agonist', accent: 'text-emerald-700', soft: 'bg-emerald-50', mechanismTitle: 'Origins & Action', mechanism: 'Psilocybin is converted into psilocin, which acts on 5-HT2A receptors and temporarily reduces rigid self-referential processing, changing perception and perspective.', highlightTitle: 'DMN suppression', highlight: 'Temporary changes in default-mode network activity can produce altered self-perception and ego dissolution.', signs: ['Dilated pupils', 'Yawning, watery eyes, and runny nose', 'Uncontrollable laughter or crying', 'Visual surfaces that appear to move', 'Motor ataxia and disorientation', 'Altered time perception'], shortTerm: ['Geometric visual imagery', 'Synesthesia', 'Nausea during onset', 'Emotional catharsis', 'Ego-boundary dissolution', 'Acute anxiety or panic'], longTerm: ['Increased openness', 'Possible reduction in depressive symptoms in clinical settings', 'Rare persistent visual disturbances', 'Possible psychosis precipitation in vulnerable people'], riskTitle: 'Foraging hazards', risk: 'Confusing Psilocybe species with deadly amatoxin-containing mushrooms can cause fatal liver failure.', emergency: 'Acute panic, disorientation, terror, or dangerous confusion call for a quiet environment, calm communication, and emergency help when safety is at risk.', emergencyNote: 'Danger: Severe seizures when combined with lithium' } satisfies Profile,
  lsd: { name: 'LSD', subtitle: 'Ergoline Psychedelic & 5-HT2A Agonist', accent: 'text-violet-700', soft: 'bg-violet-50', mechanismTitle: 'Origins & Conformation', mechanism: 'LSD is an extremely potent ergoline derivative active in micrograms. Its interaction with 5-HT2A receptors contributes to an unusually long duration of action.', highlightTitle: 'Receptor trapping', highlight: 'A molecular lid over the binding site helps LSD continue stimulating serotonin receptors for many hours.', signs: ['Pronounced pupil dilation', 'Goosebumps and sweating', 'Muscle tremors and jaw tightness', 'Extended wakefulness', 'Fixation on geometric textures', 'Rapidly shifting emotions'], shortTerm: ['Geometric visuals and tracers', 'Distortion of time', 'Synesthesia', 'Mild heart-rate and temperature elevation', 'Deep conceptual thinking', 'Acute panic or a bad trip'], longTerm: ['Changes in values or worldview', 'Hallucinogen persisting perception disorder', 'Possible psychosis precipitation', 'Rapid tolerance that resets over several days'], riskTitle: 'Adulterants & NBOMe warning', risk: 'Pure LSD is generally odorless and tasteless. Bitter tabs may indicate dangerous synthetic substitutes such as NBOMe compounds.', emergency: 'Severe disorientation, combativeness, or panic require reducing sensory stimulation and seeking emergency help if safety is threatened.', emergencyNote: 'Fatal risk: Grand mal seizures when combined with lithium' } satisfies Profile,
  suboxone: { name: 'Suboxone', subtitle: 'Buprenorphine (Partial Opioid Agonist) + Naloxone (Antagonist)', accent: 'text-cyan-700', soft: 'bg-cyan-50', mechanismTitle: 'Origins & Mechanism', mechanism: 'Suboxone combines buprenorphine, a high-affinity partial mu-opioid agonist, with naloxone to reduce opioid cravings and discourage injection misuse.', highlightTitle: 'The ceiling effect', highlight: 'Buprenorphine activation plateaus, which lowers—but does not eliminate—the risk of severe respiratory depression when used as directed.', signs: ['Constricted pupils', 'Mild sedation in people without tolerance', 'Improved functioning without withdrawal', 'Dry mouth, sweating, and constipation', 'Reduced opioid cravings'], shortTerm: ['Suppression of withdrawal and cravings', 'Pain relief', 'Mild euphoria in non-tolerant users', 'Dizziness, nausea, and lightheadedness', 'Mild respiratory depression', 'Reduced gastrointestinal motility'], longTerm: ['Physical dependence and prolonged withdrawal', 'Stabilization and harm reduction', 'Dental decay from sublingual exposure', 'Mild hormonal suppression'], riskTitle: 'Precipitated withdrawal hazard', risk: 'If taken while full opioids such as fentanyl or heroin are active, buprenorphine can displace them from receptors and trigger sudden severe withdrawal.', emergency: 'Coma, pinpoint pupils, or shallow breathing—especially when mixed with sedatives—require 911 and naloxone.', emergencyNote: 'Note: Multiple naloxone doses may be needed' } satisfies Profile,
  '7-hydroxymitragynine': { name: '7-Hydroxymitragynine (7-OH)', subtitle: 'Concentrated Kratom Alkaloid & High-Potency Mu-Opioid Agonist', accent: 'text-lime-700', soft: 'bg-lime-50', mechanismTitle: 'Origins & Pharmacodynamics', mechanism: '7-OH occurs only in trace amounts in kratom leaf but is also produced by oxidizing mitragynine into concentrated products. It acts at mu-opioid receptors with substantially greater potency than mitragynine.', highlightTitle: 'The purity jump', highlight: 'Concentrated tablets can deliver the active equivalent of large amounts of raw kratom, increasing the risk of rapid tolerance and dependence.', signs: ['Pinpoint pupils and intermittent nodding', 'Intense itching and dry mouth', 'Slow speech and motor lethargy', 'Restless limbs when a dose is delayed', 'Unusual 7-OH tablet or blister packaging'], shortTerm: ['Analgesia and warm euphoria', 'Sedation and psychomotor slowing', 'Nausea and gastrointestinal slowing', 'Low blood pressure and urinary hesitancy', 'Respiratory depression at high doses'], longTerm: ['Rapid tolerance and escalating use', 'Severe opioid-like withdrawal', 'Financial and functional harms', 'Possible liver or kidney strain from unregulated products'], riskTitle: 'Opioid-like overdose risk', risk: 'Unregulated 7-OH products may vary in potency and can cause profound sedation and respiratory depression, especially with other depressants.', emergency: 'Unarousable sleep, pinpoint pupils, breathing below 8 breaths per minute, or blue lips require 911 and naloxone.', emergencyNote: 'Emergency: Naloxone may reverse opioid-related respiratory depression' } satisfies Profile,
  tianeptine: { name: 'Tianeptine', subtitle: 'Atypical Tricyclic Compound & Mu-Opioid Agonist at High Doses', accent: 'text-red-700', soft: 'bg-red-50', mechanismTitle: 'Origins & Action', mechanism: 'Tianeptine was developed as an antidepressant but can act as a full mu-opioid agonist at supratherapeutic doses. It is sold in some retail products under names such as ZaZa, Tianaa, and TD Red.', highlightTitle: 'Brutal withdrawal', highlight: 'Frequent high-dose use can produce both opioid-like withdrawal and antidepressant rebound symptoms.', signs: ['Frequent purchases of retail supplement bottles', 'Pinpoint pupils and euphoria', 'Sweating, tremors, and agitation between doses', 'Nodding followed by restless awakenings', 'Constipation and gastrointestinal distress'], shortTerm: ['Short-lived opioid-like euphoria', 'Analgesia and anxiety relief', 'Dizziness, nausea, and vomiting', 'Craving soon after the peak', 'Respiratory depression at high doses'], longTerm: ['Rapid tolerance and dose escalation', 'Severe mixed withdrawal syndrome', 'Cardiac conduction abnormalities', 'Liver or kidney injury', 'High relapse and overdose risk'], riskTitle: 'Cardiotoxicity & dependence', risk: 'High doses can affect cardiac conduction and create severe dependence. Retail products may have inconsistent labeling and dosing.', emergency: 'Severe lethargy, pinpoint pupils, irregular heartbeat, or stopped breathing require 911 and naloxone.', emergencyNote: 'Emergency: Monitor breathing and heart rhythm' } satisfies Profile,
  dextromethorphan: { name: 'Dextromethorphan (DXM)', subtitle: 'Over-the-Counter Cough Suppressant & Dissociative at High Doses', accent: 'text-fuchsia-700', soft: 'bg-fuchsia-50', mechanismTitle: 'Origins & Metabolism', mechanism: 'DXM is metabolized into dextrorphan, which can block NMDA receptors at high doses and cause dissociation. Combination cough products may also contain dangerous acetaminophen or antihistamines.', highlightTitle: 'Four plateaus', highlight: 'Effects can shift from stimulation to severe dissociation as dose increases, making misuse difficult to predict.', signs: ['Uncoordinated robotic gait', 'Dilated pupils and nystagmus', 'Flushed skin or hives', 'Slurred, disconnected speech', 'Detachment from surroundings'], shortTerm: ['Dissociation and sensory distortion', 'Visual imagery and altered hearing', 'Increased heart rate and blood pressure', 'Nausea and vomiting', 'Disorientation and loss of pain sensation'], longTerm: ['Cognitive and memory impairment', 'Dependence on dissociative effects', 'Liver injury from combination products', 'Persistent perceptual disturbances'], riskTitle: 'Serotonin syndrome & combination products', risk: 'Large doses or combination cold medicines can cause liver injury, seizures, anticholinergic toxicity, or serotonin syndrome.', emergency: 'Rigid muscles, clonus, high fever, seizures, or severe delirium require emergency care.', emergencyNote: 'Danger: Do not combine with SSRIs, SNRIs, MAOIs, or other serotonergic drugs' } satisfies Profile,
  pregabalin: { name: 'Pregabalin', subtitle: 'Gabapentinoid & Alpha-2-Delta Calcium Channel Ligand', accent: 'text-green-700', soft: 'bg-green-50', mechanismTitle: 'Origins & Mechanism', mechanism: 'Pregabalin binds the alpha-2-delta subunit of voltage-gated calcium channels and reduces release of excitatory neurotransmitters. It does not directly activate GABA receptors.', highlightTitle: 'Opioid potentiation', highlight: 'Combining pregabalin with opioids or alcohol can greatly increase sedation and respiratory depression.', signs: ['Uncoordinated, drunken gait', 'Myoclonic jerks and muscle twitches', 'Double vision', 'Swelling of hands or feet', 'Slurred speech and sedation'], shortTerm: ['Dizziness and vertigo', 'Talkativeness and euphoria', 'Loss of balance', 'Deep sleep', 'Synergistic respiratory depression with opioids or alcohol'], longTerm: ['Physical dependence and withdrawal', 'Insomnia, sweating, and seizures after abrupt cessation', 'Weight gain and edema', 'Cognitive slowing', 'Depressive symptoms'], riskTitle: 'Sedation and respiratory depression', risk: 'Pregabalin toxicity is especially dangerous with opioids, alcohol, or other central nervous system depressants.', emergency: 'Seizures, deep coma, abnormal heart rhythm, or respiratory failure require 911.', emergencyNote: 'Emergency: Naloxone does not reverse pregabalin itself' } satisfies Profile,
  ghb: { name: 'GHB', subtitle: 'GABA-B Receptor Agonist & Rapid-Onset CNS Depressant', accent: 'text-cyan-700', soft: 'bg-cyan-50', mechanismTitle: 'Origins & Action', mechanism: 'GHB acts on GHB and GABA-B receptors. Its steep dose-response curve can move quickly from disinhibition and euphoria to deep unconsciousness and respiratory depression.', highlightTitle: 'The G-out phenomenon', highlight: 'A small difference in amount can cause a sudden transition from mild effects to an unarousable coma.', signs: ['Sudden sleep after euphoria', 'Ataxia and stumbling', 'Slurred or disorganized speech', 'Muscle twitches', 'Confusion and amnesia', 'Slow, heavy breathing'], shortTerm: ['Euphoria and lowered inhibitions', 'Dizziness and nausea', 'Unarousable sleep', 'Slow heart rate and breathing', 'Rapid waking with confusion'], longTerm: ['Severe physical dependence', 'Life-threatening withdrawal delirium', 'Hallucinations during withdrawal', 'Memory impairment', 'High vulnerability to poisoning or assault'], riskTitle: 'Steep dose-response curve', risk: 'GHB, GBL, and 1,4-butanediol can cause rapid loss of consciousness. Mixing GHB with alcohol or other depressants is especially dangerous.', emergency: 'Unresponsiveness, seizure-like movements, vomiting while unconscious, or slow breathing require 911 and recovery position.', emergencyNote: 'Fatal risk: Never combine with alcohol or sedatives' } satisfies Profile,
  oxycodone: { name: 'Oxycodone', subtitle: 'Semi-Synthetic Mu-Opioid Receptor Agonist', accent: 'text-amber-700', soft: 'bg-amber-50', mechanismTitle: 'Origins & Pharmacodynamics', mechanism: 'Oxycodone is a full mu-opioid agonist that reduces pain while depressing brainstem respiratory drive and reinforcing reward pathways.', highlightTitle: 'Counterfeit M30 danger', highlight: 'Counterfeit blue pills sold as oxycodone may contain fentanyl or nitazenes and can contain multiple lethal doses.', signs: ['Pinpoint pupils', 'Nodding off', 'Itching and dry mouth', 'Slowed speech', 'Loss of coordination', 'Constipation'], shortTerm: ['Analgesia and euphoria', 'Respiratory depression', 'Suppressed cough reflex', 'Nausea and slowed digestion', 'Low blood pressure'], longTerm: ['Dependence and craving', 'Opioid-induced hyperalgesia', 'Severe bowel dysfunction', 'Hormonal suppression', 'High relapse overdose risk'], riskTitle: 'Opioid overdose', risk: 'Respiratory depression can occur with prescribed or illicit oxycodone, and counterfeit tablets make potency impossible to predict.', emergency: 'Pinpoint pupils, slow breathing, and unconsciousness require naloxone and 911 immediately.', emergencyNote: 'Emergency: Stay with the person and repeat naloxone as directed' } satisfies Profile,
  alprazolam: { name: 'Alprazolam', subtitle: 'Short-Acting Benzodiazepine & GABA-A Modulator', accent: 'text-sky-700', soft: 'bg-sky-50', mechanismTitle: 'Origins & Action', mechanism: 'Alprazolam enhances GABA-A receptor activity, suppressing anxiety and autonomic arousal while impairing memory, coordination, and alertness.', highlightTitle: 'Rebound hyperexcitability', highlight: 'Its short duration can produce inter-dose withdrawal and dangerous rebound anxiety or seizures.', signs: ['Ataxia and stumbling', 'Slurred speech', 'Heavy eyelids and drowsiness', 'Anterograde amnesia', 'Disinhibition or agitation'], shortTerm: ['Rapid anxiety relief', 'Muscle relaxation', 'Cognitive slowing', 'Blackout states', 'Respiratory suppression with depressants'], longTerm: ['Severe physical dependence', 'Withdrawal seizures', 'Memory impairment', 'Emotional flattening', 'Rebound panic'], riskTitle: 'Benzodiazepine dependence', risk: 'Abrupt discontinuation after regular use can cause seizures and delirium. Combining alprazolam with opioids or alcohol increases overdose risk.', emergency: 'Profound stupor, slow breathing, or flaccid muscles—especially with opioids—require 911.', emergencyNote: 'Caution: Do not stop abruptly without medical supervision' } satisfies Profile,
  bromazolam: { name: 'Bromazolam', subtitle: 'Designer Triazolobenzodiazepine & Counterfeit Pill Adulterant', accent: 'text-slate-700', soft: 'bg-slate-100', mechanismTitle: 'Origins & Proliferation', mechanism: 'Bromazolam is an unapproved benzodiazepine analog increasingly found in counterfeit Xanax-style pills and illicit mixtures.', highlightTitle: 'Prolonged blackout risk', highlight: 'Unpredictable street dosing and extended sedation can create multi-hour or multi-day memory gaps.', signs: ['Severe ataxia', 'Unresponsive stupor', 'Loss of inhibition', 'Memory gaps', 'Snoring or slow breathing'], shortTerm: ['Intense sedation', 'Muscle relaxation', 'Prolonged amnesia', 'Hypotension', 'Respiratory synergy with fentanyl'], longTerm: ['Rapid tolerance', 'Withdrawal seizures', 'Unregulated impurities', 'Poly-substance overdose risk', 'Sleep and cognitive disruption'], riskTitle: 'Counterfeit benzo toxicity', risk: 'Naloxone does not reverse benzodiazepine sedation, although it should be given when opioid exposure is possible.', emergency: 'Unarousable sleep, obstructed breathing, or hypoxia require airway support, 911, and naloxone for possible opioids.', emergencyNote: 'Critical: Naloxone may not restore consciousness when bromazolam is present' } satisfies Profile,
  ritalin: { name: 'Ritalin', subtitle: 'Methylphenidate & Dopamine/Norepinephrine Reuptake Blocker', accent: 'text-indigo-700', soft: 'bg-indigo-50', mechanismTitle: 'Origins & Action', mechanism: 'Methylphenidate blocks dopamine and norepinephrine transporters, increasing catecholamines in the synapse without directly reversing transporter flow like amphetamines.', highlightTitle: 'Ethylphenidate formation', highlight: 'Combining methylphenidate with alcohol can form ethylphenidate and increase cardiovascular strain.', signs: ['Dilated pupils', 'Motor tics or facial twitching', 'Fast heart rate and high blood pressure', 'Pacing and restlessness', 'Appetite suppression'], shortTerm: ['Heightened vigilance and focus', 'Euphoria', 'Vasoconstriction', 'Dehydration and low appetite', 'Anxiety and irritability'], longTerm: ['Tolerance and escalating use', 'Insomnia', 'Tic disorders', 'Arrhythmias and stroke risk', 'Dependence and depression after stopping'], riskTitle: 'Stimulant toxicity', risk: 'Crushing or injecting tablets can expose the body to insoluble fillers and increase cardiovascular and pulmonary injury.', emergency: 'Severe hypertension, chest pain, extreme agitation, hyperthermia, hallucinations, or seizures require 911.', emergencyNote: 'Emergency: Do not use stimulants to self-treat chest pain or severe symptoms' } satisfies Profile,
  adderall: { name: 'Adderall', subtitle: 'Mixed Amphetamine Salts & Monoamine Releaser', accent: 'text-orange-700', soft: 'bg-orange-50', mechanismTitle: 'Origins & Mechanism', mechanism: 'Adderall contains dextroamphetamine and levoamphetamine salts that increase dopamine and norepinephrine release and activate TAAR1.', highlightTitle: 'Counterfeit “30s”', highlight: 'Illicit pills sold as Adderall may contain methamphetamine or fentanyl, making appearance an unreliable safety signal.', signs: ['Dilated pupils', 'Rapid speech and fixation', 'Jaw clenching', 'Fast pulse and sweating', 'Appetite suppression', 'Prolonged wakefulness'], shortTerm: ['Increased focus and energy', 'Euphoria', 'High blood pressure and heart rate', 'Reduced fatigue', 'Dry mouth and anxiety'], longTerm: ['Dopamine tolerance', 'Stimulant psychosis', 'Cardiac disease and arrhythmias', 'Severe withdrawal depression', 'Sleep disruption and malnutrition'], riskTitle: 'Stimulant psychosis & hyperthermia', risk: 'High doses can cause dangerous temperature elevation, psychosis, seizures, and cardiac strain.', emergency: 'Chest pain, temperature above 104°F, severe agitation, or seizures require 911.', emergencyNote: 'Emergency: Move to a cool area and do not restrain unless necessary for immediate safety' } satisfies Profile,
};
